# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            DanSnow's Blog
tagline:          ''
description: >
  Note for programing and Daily
url:              http://DanSnow.github.io
baseurl:          /

author:
  name:           'DanSnow'

paginate:         5

# Custom vars
version:          2.1.0

